name: "Setup"
description: "Install Node & NPM dependencies"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
      with:
        node-version-file: ".nvmrc"
        cache: npm
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
      shell: bash
