name: "Setup"
description: "Install Node & NPM dependencies"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: ".nvmrc"
        cache: npm
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
      shell: bash
