name: "Setup"
description: "Install Node & NPM dependencies"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version-file: ".nvmrc"
        cache: npm
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
      shell: bash
