name: "Setup"
description: "Install Node & NPM dependencies"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
      with:
        node-version-file: ".nvmrc"
        cache: npm
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
      shell: bash
