name: "Lint"
description: "Check files respect ESLint & Prettier rules"
runs:
  using: composite
  steps:
    - run: node ./scripts/release.mjs
      shell: bash
      env:
        RELEASER_APP_ID: ${{ secrets.RELEASER_APP_ID }}
        RELEASER_PRIVATE_KEY: ${{ secrets.RELEASER_PRIVATE_KEY }}
        RELEASER_CLIENT_ID: ${{ secrets.RELEASER_CLIENT_ID }}
        RELEASER_CLIENT_SECRET: ${{ secrets.RELEASER_CLIENT_SECRET }}
        RELEASER_INSTALLATION_ID: ${{ secrets.RELEASER_INSTALLATION_ID }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
