name: "SBOM Compliance"
description: "Check for SBOM compliance"
inputs:
  appId:
    description: GitHub App ID
    required: true
  privateKey:
    description: GitHub App Private Key
    required: true
  clientId:
    description: GitHub App Client Id
    required: true
  clientSecret:
    description: GitHub App Client Secret
    required: true
  installationId:
    description: GitHub App Installation ID
    required: true
runs:
  using: composite
  steps:
    - name: Checkout licenses
      uses: actions/checkout@v3
      with:
        repository: coveo/dependency-allowed-licenses
        path: coveo-dependency-allowed-licenses
    - name: Check SBOM compliance
      run: node ./scripts/check-sbom.mjs
      shell: bash
      env:
        RELEASER_APP_ID: ${{ inputs.appId }}
        RELEASER_PRIVATE_KEY: ${{ inputs.privateKey }}
        RELEASER_CLIENT_ID: ${{ inputs.clientId }}
        RELEASER_CLIENT_SECRET: ${{ inputs.clientSecret }}
        RELEASER_INSTALLATION_ID: ${{ inputs.installationId }}
        public: "true"
        distributed: "true"
    - name: Clean licenses repo
      run: rm -rf coveo-dependency-allowed-licenses
      shell: bash
