name: "Setup"
description: "Check for unaddressed Dependabot vulnerabilities"
inputs:
  appId:
    description: GitHub App ID
    required: true
  privateKey:
    description: GitHub App Private Key
    required: true
  clientId:
    description: GitHub App Client Id
    required: true
  clientSecret:
    description: GitHub App Client Secret
    required: true
  installationId:
    description: GitHub App Installation ID
    required: true
runs:
  using: composite
  steps:
    - name: Check Dependabot vulnerabilities
      run: node ./scripts/get-scan-results.mjs
      shell: bash
      env:
        RELEASER_APP_ID: ${{ inputs.appId }}
        RELEASER_PRIVATE_KEY: ${{ inputs.privateKey }}
        RELEASER_CLIENT_ID: ${{ inputs.clientId }}
        RELEASER_CLIENT_SECRET: ${{ inputs.clientSecret }}
        RELEASER_INSTALLATION_ID: ${{ inputs.installationId }}
