name: "Snyk Scan"
description: "Run Snyk & Snyk Code and report to GH Security Advisory"

inputs:
  fail-on-vuln:
    description: "Should the action fails if a vuln is detected?"
    required: false
    default: false
  SNYK_TOKEN:
    description: "Snyk Token"
    required: true

runs:
  using: composite
  steps:
    - name: Snyk Monitor
      if: ${{ github.event_name != 'pull_request' }}
      continue-on-error: ${{ TODO }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: npx snyk monitor
    - name: Snyk Test
      continue-on-error: ${{ TODO }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: npx snyk test --dev --sarif-file-output=./sarifs/snyk.sarif
    - name: Snyk Code
      continue-on-error: ${{ TODO }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: npx snyk code test    --dev --sarif > ./sarifs/snyk-code.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@0e9acb6e5cd338179ea69a99146ca55f796799e0 # tag=v1
      with:
        sarif_file: ./sarifs
    - name: Check SnykCode vuln
      continue-on-error: ${{ TODO }}
      if: ${{ inputs.fail-on-vuln }}
      run: node ./scripts/get-scan-results.js
