name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]
jobs:
  CI:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/lint
      - name: Unit tests
        run: npm test
      - uses: ./.github/actions/build
      - name: CD type checks
        run: tsc -p tsconfig.sancheck.json
