name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]
jobs:
  CI:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/lint
      - name: Unit tests
        run: npm test
      - uses: ./.github/actions/build
      - name: CD type checks
        run: tsc -p tsconfig.sancheck.json
