name: "Recurring Security Scan"

on:
  schedule:
    - cron: "17 2 * * 2"

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: CodeQL
        uses: ./.github/actions/codeql
        with:
          language: ${{ matrix.language }}

  snyk:
    name: Snyk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/snyk
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          fail-on-error: false
