name: "Dependency Review"
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-Review:
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@dcd6745d24727ced04f7717d953c403b6c5b832d # main
    with:
      public: true
      distributed: true
      runs-on: '["ubuntu-latest"]'
