name: "Dependency Review"
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-Review:
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@8ce6eca365702b0ad9f463a01135ba88ae6c43a8 # main
    with:
      public: true
      distributed: true
      runs-on: '["ubuntu-latest"]'
