name: "Dependency Review"
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-Review:
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@269af803546d5e81bb9b4772224e7e2a2fe1d5a1
    with:
      public: true
      distributed: true
